spreconomists_org/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url, include
from django.conf import settings
from django.contrib import admin
import views


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #url(r'^$', views.home, name='home'),
    #url(r'^about$', views.about, name='about'),
    #url(r'^events$', views.events, name='events'),
    #url(r'^gallery$', views.gallery, name='gallery'),
    #url(r'^contact$', views.contact, name='contact'),

    url(r'^', include('cms.urls')),
    url(r'^', include('cms.urls', namespace='imagestore')),

]

urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

urlpatterns = patterns('',
    url(r'^assets/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

mini_charge/models.py
# -*- coding: utf-8 -*-

from django.db import models
from imagestore.models.bases.image import BaseImage
from imagestore.models.bases.album import BaseAlbum

#from django.core.urlresolvers import reverse
from cms.models import CMSPlugin
from django.conf import settings

from livesettings.functions import config_value

class MiniChargeImage(BaseImage):

    class Meta(BaseImage.Meta):
        abstract = False
        app_label = 'mini_charge'
        db_table = 'mini_charge_image'


class MiniChargeAlbum(BaseAlbum):

    class Meta(BaseAlbum.Meta):
        abstract = False
        app_label = 'mini_charge'
        db_table = 'mini_charge_album'



class Charge(models.Model):

    '''
        Charge Model
        @see https://stripe.com/docs/api#create_charge
    '''

    def __init__(self, *args, **kwargs):
        super(Charge, self).__init__(*args, **kwargs)
        #import stripe
        #DEBUG = settings.DEBUG
        #STRIPE_TEST_MODE = config_value('laurenmcmanus', 'STRIPE_TEST_MODE')
        #if DEBUG == True or STRIPE_TEST_MODE == True:
        #    stripe.api_key = config_value('laurenmcmanus', 'STRIPE_TEST_PUBLIC_KEY')
        #else:
        #    stripe.api_key = config_value('laurenmcmanus', 'STRIPE_LIVE_PUBLIC_KEY')
        #self.stripe = stripe

    name = models.CharField(max_length=50)
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=5,
        null=True,
        blank=True)
    currency = models.CharField(
        max_length=10,
        help_text='"USD", "EUR", etc. Review https://support.stripe.com/questions/which-currencies-does-stripe-support for more detail.'
    )
    description = models.CharField(max_length=300)

    # Expect user to create a price specification before attaching
    # a work of art or product.
    work = models.ManyToManyField(MiniChargeImage)

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = 'mini_charge'


class MiniChargePluginModel(CMSPlugin):

    '''
        MiniCharge Plugin Model
    '''
    charge = models.ForeignKey(
        Charge,
        related_name='plugins'
    )

    def __unicode__(self):
        return self.charge.name

    class Meta:
        app_label = 'mini_charge'

spreconomists_org/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from website.models import EventItem

def home(request):

    '''
    @deprecated
    '''

    return render_to_response(
        'home.html',
        context_instance=RequestContext(request)
    )

def about(request):

    '''
    '''

    return render_to_response(
        'about.html',
        context_instance=RequestContext(request)
    )

def events(request):

    '''
    @deprecated
    '''
    _events = EventItem.objects.all()

    return render_to_response(
        'events.html',
        {
            'events': _events
        },
        context_instance=RequestContext(request)
    )

def gallery(request):

    '''
    '''

    return render_to_response(
        'gallery.html',
        context_instance=RequestContext(request)
    )

def contact(request):

    '''
    '''

    return render_to_response(
        'contact.html',
        context_instance=RequestContext(request)
    )

spreconomists_org/templates/cms/plugins/imagestore_album.html
{% load thumbnail %}

<ul class='gallery'>
  {% for image in album.images.all %}
    {% thumbnail image.image '400x400' crop='center' as im %}

      {% thumbnail image.image '600x600' as full %}
        <li>
          <figure
            itemscope
            itemtype="https://schema.org/Painting"
          >
            
            {% include 'mini_charge/base_plugin.tmpl' with instance=image.charge_set.all.0 %}

            <img 
              class='preview {{ im.tags }}'
              {% if image.title %}
              alt='{{ image.title }}'
              {% endif %}
              src='{{ full.url }}'
              data-title='{{ image.title }}'
              {% if image.description %}
              data-caption='{{ image.description }}'
              {% endif %}
            />

            <a 
              title="{% spaceless %}
              {% if image.title %}
                {{ image.title }}
              {% endif %}
              {% endspaceless %}"
              href="{{ full.url }}"
            >
              {% if image.title %}
              <figcaption>
                {% if image.title %}
                  <h2>{{ image.title }}</h2>
                {% endif %}
                {% if image.description %}
                  <p>{{ image.description }}</p>
                {% endif %}
              </figcaption>
              {% endif %}
            </a>
          </figure><!-- @itemtype -->

          <!--
             -<div class="mini-auction">
             -  <ul>
             -    <li></li>
             -  </ul>
             -</div>
             -->

        </li>
      {% endthumbnail %}

    {% endthumbnail %}
  {% endfor %}
</ul>

spreconomists_org/templates/cms/plugins/imagestore_album_carousel_base.html
{% load thumbnail %}

<ul
  id='carousel{{ carousel.id }}'
  class='{{ carousel.skin }}'
>
  {% for image in images %}
    {% thumbnail image.image carousel.size crop='center' as im %}
      {% thumbnail image.image carousel.full_size as full %}
        <li>
          <figure>
            <a rel='gallery{{ carousel.id }}[pp_gal]' href='{{ full.url }}'>
              <img
                class='preview'
                {% if image.title %}alt='{{ image.title }}'{% endif %}
                src='{{ im.url }}'
              />
              <figcaption>
                {% if image.title %}<h2>{{ image.title }}</h2>{% endif %}
                {% if image.description %}<p>{{ image.description }}</p>{% endif %}
              </figcaption>
            </a>
          </figure>
        </li>
      {% endthumbnail %}
    {% endthumbnail %}
  {% endfor %}
</ul>

<script type='text/javascript'>
  var CarouselContainer = (function() {
    var carousel_id = '{{ carousel.id }}';
    return {
      'carousel_id': carousel_id
    }
  })();
</script>